### PR TITLE
Added the BetaFPV Air75 Factory Defaults

### PR DESCRIPTION
**Pull request by YarosMallorca**
Added the default BetaFPV Air75 (Whoop) factory diff.
I got it from my new Air75 (bought in September 2024) which came with BF 4.5.0 from the factory.

### CODE REVIEW

**Comment by haslinghuis** [comment]
@limonspb  Think this would need a new bnf folder in 4.5.

**Comment by YarosMallorca** [comment]
My bad @haslinghuis I didn't pay attention. Refactoring now.

**Comment by limonspb** [comment]
> @limonspb Think this would need a new bnf folder in 4.5.

Yeah can just create this forlder there. No need to add it to 4.3/bnf

**Comment by YarosMallorca** [comment]
@limonspb Done, moved to `4.5/bnf`

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
