### PR TITLE
Add dual BMI270 filter settings

### PR DESCRIPTION
**Pull request by DusKing1**
Weather is bad so can't provide more flight log, marked it as experimental.

### CODE REVIEW

**Review by limonspb — APPROVED** [review]

**Comment by limonspb** [comment]
@DusKing1 is this one ready to merge in your opinion?

**Comment by DusKing1** [comment]
> @DusKing1 is this one ready to merge in your opinion?

@limonspb From my own point of view yes.

**Comment by limonspb** [comment]
> > @DusKing1 is this one ready to merge in your opinion?
> 
> @limonspb From my own point of view yes.

ok, merged. 
@ctzsnooze if you find some questions, please let us know here.
Thanks.

**Comment by ctzsnooze** [comment]
We rely on Dusking here, I haven't personally been seen any logs or done any testing.

**Pull request merged**
