### PR TITLE
Fport

### PR DESCRIPTION
**Pull request by HThuren**
Added choose between Sbus and Fport settings, and renamed frsky_sbus.txt to frskt_sbus_fport.txt
Added fport to search word

### CODE REVIEW

**Comment by limonspb** [comment]
Yeah that's cool now.
Few suggestions, add #$ FORCE_OPTIONS_REVIEW 
per #175,  because it's mandatory to choose between two options now.
And we usually keep the main author. Can't add all authors who modified the file, because it can be a long list otherwise. All authors stay in GitHub history :)

**Comment by HThuren** [comment]
> Yeah that's cool now. Few suggestions, add `#$ FORCE_OPTIONS_REVIEW` per #175, because it's mandatory to choose between two options now. And we usually keep the main author. Can't add all authors who modified the file, because it can be a long list otherwise. All authors stay in GitHub history :)

OK, changed the author, no problem :-)

But I did have the FORCE_OPTION_REVIEW statement, in line 12,, or do you want me to put it in the group **#$ OPTION_GROUP BEGIN: Sbus or FPort (choose only one)** (can't see this are allowed in the syntaks description (?)

**Comment by limonspb** [comment]
> > Yeah that's cool now. Few suggestions, add `#$ FORCE_OPTIONS_REVIEW` per #175, because it's mandatory to choose between two options now. And we usually keep the main author. Can't add all authors who modified the file, because it can be a long list otherwise. All authors stay in GitHub history :)
> 
> OK, changed the author, no problem :-)
> 
> But I did have the FORCE_OPTION_REVIEW statement, in line 12,, or do you want me to put it in the group **#$ OPTION_GROUP BEGIN: Sbus or FPort (choose only one)** (can't see this are allowed in the syntaks description (?)

Oh sorry I missed that you already had force options review.

**Comment by limonspb** [comment]
Please don't close/open PRs if you only need to squas :)

**Comment by HThuren** [comment]
Well only to squash the commite by:
git reset $(git commit-tree HEAD^{tree} -m "Added FRSKY FPort presetting")
and the push
uuuh, have never tried that command before :-)

**Comment by limonspb** [comment]
> Well only to squash the commite by: git reset $(git commit-tree HEAD^{tree} -m "Added FRSKY FPort presetting") and the push uuuh, have never tried that command before :-)

That's too complicated ))
For 6 commits:
git reset --soft HEAD~6
git commit -m "your message"
git push origin your_branch -f

**Comment by haslinghuis** [comment]
https://github.com/betaflight/betaflight/wiki/Betaflight-Contribution#squash-your-commits

````
git rebase -i HEAD~6
git push origin +branch
```

**Comment by limonspb** [comment]
> https://github.com/betaflight/betaflight/wiki/Betaflight-Contribution#squash-your-commits
> 
> ```
> git rebase -i HEAD~6
> git push origin +branch
> ```
> ```

Interactive reading is hard, way more buttons to push )

**Comment by haslinghuis** [comment]
Yeah you basically kill commits, leave changed files, and make a fresh commit with force push.

You can replace -f with + before the branch 😄

**Comment by HThuren** [comment]
Thank you, I have learned somthing new :-)
But I also managed to closed this PR, and not sure if reopen are right,, the PR state there are 192 files (?)

**Comment by HThuren** [comment]
and not using the interactive, best with bash :-)

**Comment by limonspb** [comment]
Yes, reopening is fine.
You did something wrong but easy fix.
Copy updated preset file somewhere outside.
Delete your local branch:
git checkout master
git branch -D your_branch_name
Create your new branch with the old name:
git checkout -b your_branch_name
Copy back your updated file
Commit
Then force-push
git push origin +your_branch_name

**Comment by HThuren** [comment]
Won't work, did the commands, but nothing show up at my own fork nor this PR

**Comment by haslinghuis** [comment]
Did you `commit -am "message"` ?

**Comment by HThuren** [comment]
But the HThuren:fport are right ,, phuu

**Comment by haslinghuis** [comment]
a stands for add (otherwise done with git add .)

**Comment by HThuren** [comment]
OK, before commit I did the 
git add .

**Comment by HThuren** [comment]
well, I spend your time on this. 
I think I do a new PR, there are only 1 file

Thank you for instructions, nice to (maybe) next time :-)

**Comment by haslinghuis** [comment]
but did you also do git push origin +fport after the last commands issued?

**Comment by HThuren** [comment]
yes and no, I never managed to use push without the tokken
git push -f https://myToken@github.com/HThuren/BF_firmware-presets
and then can't do 
git push ...

**Comment by HThuren** [comment]
now PR #306 (sorry)

**Pull request closed without merging**
