### PR TITLE
Added YarosFPV DJI O3 OSD

### PR DESCRIPTION
**Pull request by YarosMallorca**
Added my OSD profile for DJI O3 Quads

### CODE REVIEW

**Comment by limonspb** [comment]
It is bettert to #$ include defaults file and then just list the changes that are different from defaults.
Also your goggles battery is dead :)

**Comment by haslinghuis** [comment]
@YarosMallorca please recreate PR as it is based on master - not a feature branch.

**Comment by YarosMallorca** [comment]
@haslinghuis Can I just rename the master branch on my repository? Why does it need to be based on another branch? There is no feature branch anyway on origin.

**Comment by YarosMallorca** [comment]
Will redo it.

**Comment by YarosMallorca** [comment]
@haslinghuis New PR: https://github.com/betaflight/firmware-presets/pull/474

**Pull request closed without merging**
