### PR TITLE
IRC Ghost 250Hz support

### PR DESCRIPTION
**Pull request by daleckystepan**
Initial support for Ghost RC link.

It is my currently used conservative settings. We can discuss how to improve it or extend to other refresh rates.

### CODE REVIEW

**Comment by Canaill51** [comment]
Hi guys,
Did you have any chance to take a look at this Ghost RC Link preset?
This could help Ghost users a lot for BF4.3 :)
Thanks for your help.

**Comment by daleckystepan** [comment]
@Canaill51 It is in progress. @sugaarK is working on that.

**Comment by sugaarK** [comment]
Correct I hope to do My testing tomorrow

**Comment by limonspb** [comment]
other ghost presets are merged

**Pull request closed without merging**
