### PR TITLE
Improvements on indexer.js and presets metadata

### PR DESCRIPTION
**Pull request by limonspb**
Adding multiple metadata properties with the "advanced" parsing.
All settings and parameters now are in Settings.js

Settings.js is being added at the beginning of index.**json** together with unique values for the following properties:
`firmwareVersion, author, category, keywords`
so that configurator did not have to spend time for the initial parsing.

Index file content now is the following:
```
        this.settings = settings;
        this.uniqueValues = {};
        this.presets = presetFilesArray;

        this.uniqueValues.firmwareVersion = this._getUniqueValues(presetFilesArray, "firmwareVersion");
        this.uniqueValues.category = this._getUniqueValues(presetFilesArray, "category");
        this.uniqueValues.author = this._getUniqueValues(presetFilesArray, "author");
        this.uniqueValues.keywords = this._getUniqueValues(presetFilesArray, "keywords");
```
index.json doesn't replicate the folder structure anymore, instead just creates an array of preset files for easy user search in Configurator.

Proposed template for presets:
```
# Title: Preset title
# FirmwareVersion: 4.2
# FirmwareVersion: 4.3 (as many versions as needed)
# Category: TUNE
# Official: true
# Keywords: word1, word2, word3
# Author: Name Lastname Pilotname
# Description: Description line1
# Description: Description line2  (as many description lines as needed)
# Defaults: path/to/defaults.txt

<cli command 1>
<cli command 2>
....
<cli command n>
```

Categories:
`TUNE, RATES, OSD, VTX, LEDS, MODES, BNF, RC_SMOOTHING, MIXED`

index_hash.txt file is being created next to index.json for future optimizations on the Configurator side.

### CODE REVIEW

**Comment by mikeller** [comment]
@limonspb: What was the directory structure that we'd agreed on? Thinking that the `# Official` header might be incorporated into the directory structure (`/official/...` vs. `/community/...`) - this would allow for easy handling of pull request approval rules.

**Comment by limonspb** [comment]
@mikeller I think yes, like this:
/presets/community/tune
/presets/official/tune
/presets/community/rates

But I do not want to remove # Official or # Category from the metadata in case later we want to group folders differently.

This way we can change folder structures as we want later without worrying about messing presets in the Configurator.

**Comment by mikeller** [comment]
Fair enough - I guess in this case we can use the indexer to check if the directory and the metadata matches for every file, and return an error otherwise.

**Comment by mikeller** [comment]
What is `index_hash.txt` meant for?

**Review by mikeller — APPROVED** [review]

**Comment by limonspb** [comment]
> What is `index_hash.txt` meant for?
for future optimizations. So that client could download a small file first and see if he needs to update the whole index.json that can be potentially big. Can be useful when the user just switching between tabs with slow internet.

**Comment by mikeller** [comment]
@limonspb: Not sure we even need to generate this hash ourselves - have a look at how we are getting file information for Unified Target configurations in Betaflight configurator:

https://github.com/betaflight/betaflight-configurator/blob/642a4a45793bb1758914df1377194440e9ffc31d/src/js/GitHubApi.js#L10-L27

**Comment by limonspb** [comment]
> @limonspb: Not sure we even need to generate this hash ourselves - have a look at how we are getting file information for Unified Target configurations in Betaflight configurator:
> 
> https://github.com/betaflight/betaflight-configurator/blob/642a4a45793bb1758914df1377194440e9ffc31d/src/js/GitHubApi.js#L10-L27

Interesting. @mikeller , isn't it making an extra API request and we have limited number of them?

**Comment by mikeller** [comment]
@limonspb: This will be one single request, which can be cached per configurator installation, and limited to be done every couple of hours, so this should not be a problem.

**Pull request merged**
