### PR TITLE
Adding UAV_tech_Cinewhoop

### PR DESCRIPTION
**Pull request by spatzengr**
PID Tab:
image

Filters Tab:
image

48K Option:
image

96K Option:
image

RPM Filter Option:
image

Dynamic Idle Option:
image

### CODE REVIEW

**Review by limonspb — APPROVED** [review]

**Review by limonspb — APPROVED** [review]

**Review by limonspb — APPROVED** [review]

**Comment by Kevin590** [comment]
I had to turn down the Master Multiplier from 1.6 to 1.0, my motors ran to hot at 1.6 and fairly warm at 1.2.

My build:
- HGLRC Veyron 30CR Frame (no bumpers)
- HAKRC F722 45A AIO FC
- Hypershot 1507.5 3922 kv motors
- 4S 1000mah - 1300mah batteries

I've attached the blackbox log from the PIDToolbox Step Response Tool, there is some overshoot and oscillations,
but not bad. I was able to smooth the tune out in the tool, but I didn't like how it flew with those settings as much as I like this tune with the Master Multiplier at 1.0 being the only change. I may tweak it some more.

Screen Shot 2022-04-06 at 8 54 43 PM

**Comment by course-up** [comment]
I tried Betaflight 4.3 RC5 with the preset "**UAV Tach Cinewhoop**" with the options "**_48k ESC PWM_**", "**_RPM filtering_**" and "**_Dynamic Idle_**". For RC-Link settings I use "**ExpressLRS 250Hz**" preset with the options: "**_Cineamatic_**" and "**_Serial, separate Rx_**". 

I flew 4 packs in gusty winds (3 to 5 Beaufort) and it was fantastic! The best tune on the Slammed Squirt so far! Thank you UAV Tech!

My setup:
- T-Motor 2203.5 2850kv
- IFlight Beast F7 45A AIO (ESC 48kHz, Bluejay 0.16)
- HQProp 75mm CineWhoop 3" 6-Blade
- GoPro Hero 8
- 76mm Ducts (PCTPE)
- Ovonic 1000mAh 6S

**Comment by Max-Headroom** [comment]
The video from JB on dynamic idle is for BF4.1 and out dated. Although, his explanation on the how and why is good, but the tuning is different. Changes where made in 4.2 and it was even more simplified in 4.3.
I would suggest this BF wiki: https://github.com/betaflight/betaflight/wiki/Tuning-Dynamic-Idle

**Comment by limonspb** [comment]
@spatzengr saw this preset got AG gain of 10, is that ok? Seems a bit too high, what do you think?

**Comment by eliazanetta276** [comment]
ho un beta 95x v3, come mi consigliate di settare il preset?

**Comment by limonspb** [comment]
> ho un beta 95x v3, come mi consigliate di settare il preset?

plz English

**Comment by eliazanetta276** [comment]
I have a beta 95x v3, how do you recommend setting the  cinewhoop preset?


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Ivan ***@***.***>
Inviato: martedì 18 luglio 2023 01:14
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [betaflight/firmware-presets] Adding UAV_tech_Cinewhoop (PR #208)


ho un beta 95x v3, come mi consigliate di settare il preset?

plz English

**Pull request merged**
