### PR TITLE
Adding UAV_tech_Toothpic

### PR DESCRIPTION
**Pull request by spatzengr**
PID Tab:
image

Filters Tab:
image

48K Option:
image

96K Option:
image

RPM Filter Option:
image

Dynamic Idle Option:
image

### CODE REVIEW

**Review by limonspb — APPROVED** [review]

**Review by limonspb — APPROVED** [review]

**Comment by Bryanw55** [comment]
Used this preset on a very light naked vista build. It really smoothed things out over the stock tune, particularly when dropping down through propwash and on fast yaw direction changes. Dynamic idle is helping me improve my proximity flips and rolls, keeping them tighter. Thanks!

**Comment by dxcoil** [comment]
Hello,
i use your preset and thank you for this. i have one question, if i use your preset my Dmax slider is completly set to zero, is this correct??
image

**Comment by spatzengr** [comment]
@dxcoil , correct.  Constant D-gain lets you push up the Master Slider to peak performance.

**Comment by dxcoil** [comment]
Thanks a lot for your quick reply, i apreciate your work a lot and since your preset i watch all your youtube video´s great double thanks.
since i use your preset i have feeling that i have personaly a little bite more issues to hold hight, do you now with setting i can influence this, or maybe it is onyl a feeling since i´m not a pro. my regards from germany

**Pull request merged**
