### PR TITLE
Supafly 4.5 Presets with minor tweaks

### PR DESCRIPTION
**Pull request by SupaflyFPV**
Transfer 4.4 Presets to 4.5 with minor tweaks

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Comment by limonspb** [comment]
@SupaflyFPV  why the new preset files should be created? Could just add 4.5 to the old ones?

**Review by limonspb — CHANGES_REQUESTED** [review]
@SupaflyFPV why the new preset files should be created? Could just add 4.5 to the old ones?

**Comment by SupaflyFPV** [comment]
> @SupaflyFPV why the new preset files should be created? Could just add 4.5 to the old ones?

to be honest, I just followed UAV Tech's lead on this...I'm not clear on how we structure each version release on presets...

**Comment by limonspb** [comment]
> > @SupaflyFPV why the new preset files should be created? Could just add 4.5 to the old ones?
> 
> to be honest, I just followed UAV Tech's lead on this...I'm not clear on how we structure each version release on presets...

if your previous presets are good for 4.5, which i believe they are, then you can jsut add another firmware version in the file.
There is a small difficulty because filter defaults.txt should be updated for 4.5.
But i will figure something out for that.

**Comment by SupaflyFPV** [comment]
> > > @SupaflyFPV why the new preset files should be created? Could just add 4.5 to the old ones?
> > 
> > 
> > to be honest, I just followed UAV Tech's lead on this...I'm not clear on how we structure each version release on presets...
> 
> if your previous presets are good for 4.5, which i believe they are, then you can jsut add another firmware version in the file. There is a small difficulty because filter defaults.txt should be updated for 4.5. But i will figure something out for that.

Im happy to adjust my 4.4 preset then add 4.5 to it - but how are the defaults dealt with? And should I close this PR?

**Comment by limonspb** [comment]
> Im happy to adjust my 4.4 preset then add 4.5 to it - but how are the defaults dealt with? And should I close this PR?

Thanks!
in the defaults.txt i will replace direct parameters resetting with something like:
```
defaults group_id 544 nosave #PG_RPM_FILTER_CONFIG
defaults group_id 14 nosave #PG_PID_PROFILE
defaults group_id 10 nosave #PG_GYRO_CONFIG
```
so just include 4.3 or 4.4 defaults for tune/filters.

about PR - whatever is more convinient for you, i don't mind.

**Pull request closed without merging**
