### PR TITLE
Adding Betafpv A01 VTX table with Pilot Ebel setting

### PR DESCRIPTION
**Pull request by gonebdg**
**Set VTX settings and table to Betafpv A01 Pilot Ebel**

1. Switches on TBS SmartAudio for SOFTSERIAL1 port with AUTO baud rate setting
2. Set VTX table for Betafpv A01
3. Set VTX settings to default Pilot Ebel configuration (including OSD element)

### CODE REVIEW

**Comment by limonspb** [comment]
Hi! Please make sure you check these tips for preset authors:
https://github.com/betaflight/firmware-presets#tips-for-authors

**Comment by gonebdg** [comment]
> Hi! Please make sure you check these tips for preset authors: https://github.com/betaflight/firmware-presets#tips-for-authors
> 
> I think serial/Uart settings should be removed or brought into unchecked options. Because not everyone will use it on softserial 1. Same for low power on disarm setting and default vtx/power.

How to make this options (optional settings) able to be chosen by users ?

**Comment by limonspb** [comment]
> > Hi! Please make sure you check these tips for preset authors: https://github.com/betaflight/firmware-presets#tips-for-authors
> > I think serial/Uart settings should be removed or brought into unchecked options. Because not everyone will use it on softserial 1. Same for low power on disarm setting and default vtx/power.
> 
> How to make this options (optional settings) able to be chosen by users ?

All described in detailed in the main presets readme:
https://github.com/betaflight/firmware-presets

And you can always check the other presets, how it's done there.

**Comment by limonspb** [comment]
plz make sure you read tips for authors and plz make sure you check other vtx presets

**Comment by gonebdg** [comment]
> > > Hi! Please make sure you check these tips for preset authors: https://github.com/betaflight/firmware-presets#tips-for-authors
> > > I think serial/Uart settings should be removed or brought into unchecked options. Because not everyone will use it on softserial 1. Same for low power on disarm setting and default vtx/power.
> > 
> > 
> > How to make this options (optional settings) able to be chosen by users ?
> 
> All described in details in the main presets readme: https://github.com/betaflight/firmware-presets
> 
> And you can always check the other presets, how it's done there.

Thanks, updated. Now the option 1 & 3 are optional while the option 2 is mandatory
image

**Comment by limonspb** [comment]
> > > > Hi! Please make sure you check these tips for preset authors: https://github.com/betaflight/firmware-presets#tips-for-authors
> > > > I think serial/Uart settings should be removed or brought into unchecked options. Because not everyone will use it on softserial 1. Same for low power on disarm setting and default vtx/power.
> > > 
> > > 
> > > How to make this options (optional settings) able to be chosen by users ?
> > 
> > 
> > All described in details in the main presets readme: https://github.com/betaflight/firmware-presets
> > And you can always check the other presets, how it's done there.
> 
> Thanks, updated. Now the option 1 & 3 are optional while the option 2 is mandatory image

plz make sure you read the tips for the authors i mentioned above.
And make sure you check the other VTX presets.

**Comment by gonebdg** [comment]
> plz make sure you read the tips for the authors i mentioned above. And make sure you check the other VTX presets.

image
ok I decide to add the mandatory as checked option and add more descriptions including link to discussion.
Is there another thing I have to fix/update or something I missed for my 1st preset contribution and PR?
Thanks

**Comment by limonspb** [comment]
> > plz make sure you read the tips for the authors i mentioned above. And make sure you check the other VTX presets.
> 
> image ok I decide to add the mandatory as checked option and add more descriptions including link to discussion. Is there another thing I have to fix/update or something I missed for my 1st preset contribution and PR? Thanks

did you open the link with the tips for authors?

**Comment by gonebdg** [comment]
> did you open the link with the tips for authors?
Sure, is there something missed or something wrong ?

**Comment by KarateBrot** [comment]
> Sure, is there something missed or something wrong ?

-----

Unfortunately there is. The updated index files are part of your PR as seen in the changes https://github.com/betaflight/firmware-presets/pull/284/files. But the tips say

pic0

Also there is another problem. You have multiple commits but the tips say

grafik


But don't worry, those are easy to fix 🙂

-----

### How to fix

Open the terminal and direct it to the firmware-presets folder. Now type
```
git reset --soft HEAD~3
git reset HEAD "index.json"
git reset HEAD "index_hash.json"
git commit -m "Adding Betafpv A01 VTX table with Pilot Ebel setting"
git push --force
```

This should revert the last 3 commits, then exclude these two files, make 1 new commit and then update your PR. If it doesn't work or you run into problems or have any questions feel free to ask. 🤙

**Comment by gonebdg** [comment]
> 
> This should revert the last 3 commits, then exclude the index files, then make 1 new commit and then update your PR. If it doesn't work for some reason or if you run into problems or if you have any questions feel free to ask. 🤙

I've got this error 
image

**Comment by KarateBrot** [comment]
Try
```
git fetch
git pull
git push --set-upstream origin add-betafpv-a001-pilot-ebel
```

Then try to execute [the commands from my previous comment](https://github.com/betaflight/firmware-presets/pull/284#issuecomment-1250065076) again.

**Comment by gonebdg** [comment]
> Try
> 
> ```
> git fetch
> git pull
> git push --set-upstream origin add-betafpv-a001-pilot-ebel
> ```
> 
> Then try to execute [the commands from my previous comment](https://github.com/betaflight/firmware-presets/pull/284#issuecomment-1250065076) again.

another error
image

then I execute following cmd
image

**Comment by limonspb** [comment]
> > Try
> > ```
> > git fetch
> > git pull
> > git push --set-upstream origin add-betafpv-a001-pilot-ebel
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then try to execute [the commands from my previous comment](https://github.com/betaflight/firmware-presets/pull/284#issuecomment-1250065076) again.

Could you navigate inside .git folder (hidden folder) in your local repo, open .gitconfig file as a text, and show what's there?
Most likely you just need:
`git push origin add-betafpv-a001-pilot-ebel -f`
if origin is already setup in .gitconfig and pointing at your github fork.

**Comment by gonebdg** [comment]
> Could you navigate inside `.git` folder (hidden folder) in your local repo, open `.gitconfig` file as a text, and show what's there? Most likely you just need: `git push origin add-betafpv-a001-pilot-ebel -f` if origin is already setup in .gitconfig and pointing at your github fork.

here my config file content `\git\firmware-presets\.git\config`
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/gonebdg/firmware-presets.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by limonspb** [comment]
@gonebdg 
yeah you just need:
`git push origin add-betafpv-a001-pilot-ebel -f`
don't forget -f cuz you will be overwriting existing commits with a single commit you created locally

**Comment by limonspb** [comment]
> > @gonebdg yeah you just need: `git push origin add-betafpv-a001-pilot-ebel -f` don't forget -f cuz you will be overwriting existing commits with a single commit you created locally
> 
> **Done** There is a typo in your cmd 😄 ... but I fix it image

git checkout add-betafpv-a01-pilot-ebel
git reset --soft HEAD~3
git reset HEAD "index.json"
git reset HEAD "index_hash.txt"
git commit -m "Adding Betafpv A01 VTX table with Pilot Ebel setting"
git push origin add-betafpv-a01-pilot-ebel -f

**Comment by gonebdg** [comment]
> > > @gonebdg yeah you just need: `git push origin add-betafpv-a001-pilot-ebel -f` don't forget -f cuz you will be overwriting existing commits with a single commit you created locally
> > 
> > 
> > **Done** There is a typo in your cmd 😄 ... but I fix it image
> 
> ```
> git checkout add-betafpv-a01-pilot-ebel
> git reset --soft HEAD~3
> git reset HEAD "index.json"
> git reset HEAD "index_hash.txt"
> git commit -m "Adding Betafpv A01 VTX table with Pilot Ebel setting"
> git push origin add-betafpv-a01-pilot-ebel -f
> ```

eh ... I thought it already done previously, removing index
image

**Comment by limonspb** [comment]
> > > > @gonebdg yeah you just need: `git push origin add-betafpv-a001-pilot-ebel -f` don't forget -f cuz you will be overwriting existing commits with a single commit you created locally
> > > 
> > > 
> > > **Done** There is a typo in your cmd 😄 ... but I fix it image
> > 
> > 
> > ```
> > git checkout add-betafpv-a01-pilot-ebel
> > git reset --soft HEAD~3
> > git reset HEAD "index.json"
> > git reset HEAD "index_hash.txt"
> > git commit -m "Adding Betafpv A01 VTX table with Pilot Ebel setting"
> > git push origin add-betafpv-a01-pilot-ebel -f
> > ```
> 
> eh ... I thought it already done previously, removing index image

Ok.
Save your preset file separately.
Remove your local branch (not on GitHub just locally)
Make a new branch with the same name based on master.
Copy in your preset file and commit
Then force-push 

But you also need to work on your preset file.
You didn't check how other vtx tables are done. Read description for them, check how they deal with warnings, disclaimers, #discussion etc. Please read the tips for authors carefully again. Don't tell me you did cuz you didn't )))

**Comment by gonebdg** [comment]
> 
> Ok. Save your preset file separately. Remove your local branch (not on GitHub just locally) Make a new branch with the same name based on master. Copy in your preset file and commit Then force-push
> 
> But you also need to work on your preset file. You didn't check how other vtx tables are done. Read description for them, check how they deal with warnings, disclaimers, #discussion etc. Please read the tips for authors carefully again. Don't tell me you did cuz you didn't )))

I don't know what is wrong with my current preset file content
https://github.com/gonebdg/firmware-presets/blob/add-betafpv-a01-pilot-ebel/presets/4.3/vtx/Betafpv_A01_Pilot_Ebel.txt

**Comment by gonebdg** [comment]
@limonspb 
it's done
image

**Comment by limonspb** [comment]
> > Ok. Save your preset file separately. Remove your local branch (not on GitHub just locally) Make a new branch with the same name based on master. Copy in your preset file and commit Then force-push
> > But you also need to work on your preset file. You didn't check how other vtx tables are done. Read description for them, check how they deal with warnings, disclaimers, #discussion etc. Please read the tips for authors carefully again. Don't tell me you did cuz you didn't )))
> 
> I don't know what is wrong with my current preset file content https://github.com/gonebdg/firmware-presets/blob/add-betafpv-a01-pilot-ebel/presets/4.3/vtx/Betafpv_A01_Pilot_Ebel.txt

i just listed whats wrong and what actions are required.

**Pull request closed without merging**
