### PR TITLE
Update karate_race_lite.txt

### PR DESCRIPTION
**Pull request by sugaarK**
MOVE TO COMMUNITY PRESETS

### CODE REVIEW

**Review by limonspb — APPROVED** [review]

**Review by limonspb — CHANGES_REQUESTED** [review]
Oh lol, you didn't run the check.js, did you? :)
image

**Comment by sugaarK** [comment]
Yeah of course I did!!

**Comment by limonspb** [comment]
> Yeah of course I did!!

You did not :)

**Comment by sugaarK** [comment]
I’ll fix it when I get home

**Review by limonspb — APPROVED** [review]

**Pull request merged**
