### PR TITLE
Adding UAV_tech_Analog

### PR DESCRIPTION
**Pull request by spatzengr**
image

### CODE REVIEW

**Review by limonspb — CHANGES_REQUESTED** [review]
probably worth mentioning if that's PAL or NTSC or give options.

**Comment by spatzengr** [comment]
> probably worth mentioning if that's PAL or NTSC or give options.

Noted NTSC

**Review by limonspb — APPROVED** [review]

**Comment by Snyperx** [comment]
I seem to get a bunch indicated errors when I select this for my 3" drone. I am running a HGLRC Zeus VTX with Caddx ANT camera. Please advise. Thanks

**Comment by limonspb** [comment]
> I seem to get a bunch indicated errors when I select this for my 3" drone. I am running a HGLRC Zeus VTX with Caddx ANT camera. Please advise. Thanks

It be helpful if you share screenshot of the errors

**Pull request merged**
