### PR TITLE
Adding UAV_tech_8-9in

### PR DESCRIPTION
**Pull request by spatzengr**
PID Tab:
image

Filters Tab:
image

48K Option:
image

RPM Filter Option:
image

Dynamic Idle Option:
image

### CODE REVIEW

**Review by limonspb — APPROVED** [review]

**Review by limonspb — APPROVED** [review]

**Comment by Joerg-H-Wagner** [comment]
With this preset I had a fly-away in idle with approx. 30mph.
P-Term is weigh too much. My 8" copter's weight is 808g including battery. 
Sorry, but I will never trust tuning presets anymore.

**Comment by spatzengr** [comment]
Agreed.  This is the same as the 4.2 preset I had for years with over 90 people reviewed and it has 4.5 Stars.  So granted, maybe not right for your quad, but that is because of an unlying issue.  Probably with too much mechanical vibration.

I have a 10" I'll be tuning again soon and will be seeing how it does on that one.  It has crazy motors though so should be interesting (3115s!).

image

**Comment by Joerg-H-Wagner** [comment]
Hello. I made another flight tests with log files just for you. Copter's weight including battery is now 1040g. A metal block underneath (1100g) with bindings in addition and some space should prevent fly-aways. But nevertheless, it carries the extra weight and flies. Equipment: Brotherhobby Avenger 2810 1500KV, Gemfan 8" 2-blade 6.0 pitch, BF 4.3RC7, 48kHz (byRPM), DShot, RPM Filtering. These props were already used on Chimera 7 (2806.5 1800KV) without issues.
Logfile 1: Defaults, Dynamic Dampening 0.1; Logfile 2: Angle Mode, UAV Preset; Logfile 3: Acro Mode, UAV Preset
[logfiles.zip](https://github.com/betaflight/firmware-presets/files/8874228/logfiles.zip)
.

**Comment by spatzengr** [comment]
> Logfile 1: Defaults, Dynamic Dampening 0.1; Logfile 2: Angle Mode 70% SCALED, UAV Preset; Logfile 3: Acro Mode 100% SCALED, UAV Preset [logfiles.zip](https://github.com/betaflight/firmware-presets/files/8874228/logfiles.zip) .

The longest log data is 4 seconds (the one is only 0.5 seconds long).

Nevertheless, it seems I would try moving down the Master Slider for this craft to 1.0.  Also Anti-Gravity gain to 3.5.  The rest should be fine.

**Comment by Joerg-H-Wagner** [comment]
Hello. I applied your proposal. Would be a still a fly-away if I would not tie it up. And that's the reason why some logfiles are short (Emergency disarm).
[btfl_004.bbl.zip](https://github.com/betaflight/firmware-presets/files/8878937/btfl_004.bbl.zip)

**Comment by Joerg-H-Wagner** [comment]
Thank you for your time.

**Comment by Termin-X** [comment]
hello. My first buildable quadcopter. Try. I wanted to assemble a long-range aircraft. Reduced weight. Didn't think it through. Copter when turned on (arming) - gains gas (acceleration of the propellers). Very fast. I know - weak ESC. She is one. lighter than 4pcs. separately. For safety (protection against overload), I set 0.75 power in the ESC firmware. Try to reduce - the behavior does not change. Reduced throttling (gas) when arming - does not change. I flashed one of the ready-made firmware - it began to bounce when it was turned off (arming). Unfortunately, I did not remember the version of the workpiece (preset).
in your first screenshot the position of "damping D" "tracking" "Stick respoze" is shifted to the right. Perhaps in my preset they were much to the left.
I don't understand what's wrong.
there is a description - but they often have more options available. in the video - unfortunately I can not translate the terms. in most descriptions, the authors skip complex settings (referring to the fact that beginners don’t need it. maybe they don’t know themselves :) )

assembly:
Mamba 722 mini i2c
esc 40a 4in1 (half power in firmware)
Emax eco2 2807
carbon 7"
7"*3.5*3 props
4s 2000mAh 50C
fpv 4k ssd camera
Flysky FS-i6X

Betaflight - Configurator 10,4,1   (end +10,8,0)
BLHeli - Configurator 1,1,0

**Comment by limonspb** [comment]
> hello. My first buildable quadcopter. Try. I wanted to assemble a long-range aircraft. Reduced weight. Didn't think it through. Copter when turned on (arming) - gains gas (acceleration of the propellers). Very fast. I know - weak ESC. She is one. lighter than 4pcs. separately. For safety (protection against overload), I set 0.75 power in the ESC firmware. Try to reduce - the behavior does not change. Reduced throttling (gas) when arming - does not change. I flashed one of the ready-made firmware - it began to bounce when it was turned off (arming). Unfortunately, I did not remember the version of the workpiece (preset). in your first screenshot the position of "damping D" "tracking" "Stick respoze" is shifted to the right. Perhaps in my preset they were much to the left. I don't understand what's wrong. there is a description - but they often have more options available. in the video - unfortunately I can not translate the terms. in most descriptions, the authors skip complex settings (referring to the fact that beginners don’t need it. maybe they don’t know themselves :) )
> 
> assembly: Mamba 722 mini i2c esc 40a 4in1 (half power in firmware) Emax eco2 2807 carbon 7" 7"_3.5_3 props 4s 2000mAh 50C fpv 4k ssd camera Flysky FS-i6X
> 
> Betaflight - Configurator 10,4,1 (end +10,8,0) BLHeli - Configurator 1,1,0

Hi. This is feedback for a particular preset in BF 4.3.
If you need a general help with the drone, you can ask in Betaflight discord, share your diff, black box etc there.

**Comment by Termin-X** [comment]
OK. I don't know which thread to ask. I don't understand the problem. since the preset smoothed out / masked the problem - I thought it was in these settings. the configurations are similar.

**Comment by limonspb** [comment]
> OK. I don't know which thread to ask. I don't understand the problem. since the preset smoothed out / masked the problem - I thought it was in these settings. the configurations are similar.

There is a support channel in discord. There is also betaflight Facebook grouop. This thread is not for troubleshooting your drone, it's for feedback about a particular preset. Plz stop messaging here not related things.

**Pull request merged**
