### PR TITLE
update a few of my presets

### PR DESCRIPTION
**Pull request by sugaarK**
update a few of the karate presets and adding elrs to the keywords on the 1000hz preset

### CODE REVIEW

**Comment by limonspb** [comment]
i had one guy recently complaining about weird wobbles on the latest karate preset. Here is his log:
[btfl_001.bbl.txt](https://github.com/betaflight/firmware-presets/files/11162033/btfl_001.bbl.txt)

wondering ig it could be because of the karate switch to sliders, but the pid values are somewhat off?

**Comment by sugaarK** [comment]
> i had one guy recently complaining about weird wobbles on the latest karate preset. Here is his log: [btfl_001.bbl.txt](https://github.com/betaflight/firmware-presets/files/11162033/btfl_001.bbl.txt) (remove .txt)
> 
> wondering ig it could be because of the karate switch to sliders, but the pid values are somewhat off?
> 
> Also was thinking that dyn_notch_min_hz = 200 is too spicy for lots of drones out there. That's why we have changed the defaults to 100hz? And it some options you have it even at 250hz. It could be fine for Openracer/Viper, but think about other frame manufacturers lol

looked at the log its pretty clean and looks good  I agree on the dynamic the min should be 125 I think so It can catch any frame res.. other wise there isn't any thing bad in his log.. what's his PWM settings on the quad? I recommend 48khz locked pretty much always maybe it needs to be in the notes for the present what do you think @limonspb

**Comment by limonspb** [comment]
> > i had one guy recently complaining about weird wobbles on the latest karate preset. Here is his log: [btfl_001.bbl.txt](https://github.com/betaflight/firmware-presets/files/11162033/btfl_001.bbl.txt) (remove .txt)
> > wondering ig it could be because of the karate switch to sliders, but the pid values are somewhat off?
> > Also was thinking that dyn_notch_min_hz = 200 is too spicy for lots of drones out there. That's why we have changed the defaults to 100hz? And it some options you have it even at 250hz. It could be fine for Openracer/Viper, but think about other frame manufacturers lol
> 
> looked at the log its pretty clean and looks good I agree on the dynamic the min should be 125 I think so It can catch any frame res.. other wise there isn't any thing bad in his log.. what's his PWM settings on the quad? I recommend 48khz locked pretty much always maybe it needs to be in the notes for the present what do you think @limonspb got more info from the pilot on the wobbles? im not seeing any thing obvious in the log

i think he was talking about these relatively slow wobbles: see its 30-40 degrees/sec off in some cases:
image

**Comment by sugaarK** [comment]
ahh that's throbbles... bad CG would have a big impact on this as would using dynamic idle.. this is a case by case issue that a preset couldn't possibly  handle.. he could also try some thrust linear to try and help

**Comment by limonspb** [comment]
> ahh that's throbbles... bad CG would have a big impact on this as would using dynamic idle.. this is a case by case issue that a preset couldn't possibly handle.. he could also try some thrust linear to try and help

ok cool.
i haven't tried myself the new version of the preset. And that was just a single feedback i had. So just making sure its ready to be official

**Comment by limonspb** [comment]
> ahh that's throbbles... bad CG would have a big impact on this as would using dynamic idle.. this is a case by case issue that a preset couldn't possibly handle.. he could also try some thrust linear to try and help

ps: you sure you don't want to also lower `set dyn_notch_min_hz = 250` to something smaller? :)

**Comment by sugaarK** [comment]
> > ahh that's throbbles... bad CG would have a big impact on this as would using dynamic idle.. this is a case by case issue that a preset couldn't possibly handle.. he could also try some thrust linear to try and help
> 
> ok cool. i haven't tried myself the new version of the preset. And that was just a single feedback i had. So just making sure its ready to be official

your not gona get throbbles if you don't zero the throttle so you might not get them at all..

**Comment by sugaarK** [comment]
> > ahh that's throbbles... bad CG would have a big impact on this as would using dynamic idle.. this is a case by case issue that a preset couldn't possibly handle.. he could also try some thrust linear to try and help
> 
> ps: you sure you don't want to also lower `set dyn_notch_min_hz = 250` to something smaller? :)

that's for the spicy tune.. its not for every one but works fine with a lot of quads

**Comment by limonspb** [comment]
> > > ahh that's throbbles... bad CG would have a big impact on this as would using dynamic idle.. this is a case by case issue that a preset couldn't possibly handle.. he could also try some thrust linear to try and help
> > 
> > 
> > ps: you sure you don't want to also lower `set dyn_notch_min_hz = 250` to something smaller? :)
> 
> that's for the spicy tune.. its not for every one but works fine with a lot of quads

i just not aware of any downsides of running lower min hz for dynamic notch. So it might cover more drones without much downsides if we lower it?

**Comment by sugaarK** [comment]
200hz?

**Comment by limonspb** [comment]
> 200hz?

you decide lol. I'm just asking questions to mess it all up :))

**Comment by sugaarK** [comment]
the point of the spicy is to reduce filter delay... 200 I think is good

**Comment by sugaarK** [comment]
done

**Comment by limonspb** [comment]
> the point of the spicy is to reduce filter delay... 200 I think is good

as far as i understand, if you have it at 100Hz, its not going to increase delay unless your quad needs a notch at 120hz.
And if it needs 120Hz notch, its better have it than don't :)

**Comment by sugaarK** [comment]
> > the point of the spicy is to reduce filter delay... 200 I think is good
> 
> as far as i understand, if you have it at 100Hz, its not going to increase delay unless your quad needs a notch at 120hz. And if it needs 120Hz notch, its better have it than don't :)

if you need notches at 120hz your setup isn't good enough to run the spicy tune.....

**Review by limonspb — APPROVED** [review]

**Pull request merged**
