### PR TITLE
Headsup rates

### PR DESCRIPTION
**Pull request by limonspb**
Famous 533 racing rates by Headsup - Evan Turner.
Unchecked option - close ACTUAL rates analogue.

image

### CODE REVIEW

**Review by ctzsnooze — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]
Good stuff @limonspb

**Comment by IllusionFpv** [comment]
Almost 1:1 with quick rates :)
Screenshot 2021-11-28 10 41 32

**Comment by L1cardo** [comment]
Hello guys, where does that `rate_limit = 1998` come from?
image
image

**Comment by limonspb** [comment]
> Hello guys, where does that `rate_limit = 1998` come from? image image

i think its baked in the defaults

**Pull request merged**
