### PR TITLE
Adding YaanFPV Ratebank

### PR DESCRIPTION
**Pull request by yaanfpv**
Added rates for Racing, Racing with High Yaw, Cinematic, Cinematic Chases, Smooth Freestyle and Fast Freestyle.

**Racing**
Racing

**Racing High Yaw**
Racing_HighYaw

**Cinematic**
Cinematic

**Cinematic Chase**
Cinematic_Chase

**Smooth Freestyle**
Smooth_Freestyle

**Fast Freestyle**
Fast_Freestyle

### CODE REVIEW

**Review by limonspb — CHANGES_REQUESTED** [review]
Hello!

Thanks for your PR.

PR should not include index and index_hash. These files are only for your testing.
Also PR should be presented with one commit message.
If you decide to fix the things mentioned above, please don't open a new PR, keep working in this PR.

We are at the point when we have to ask authors to justify, why they are adding rate presets.
The idea is that presets in the official repo must be interesting for many/some people.
For example, the author can be a fast racer is some country/area, a famous Youtuber, Betaflight contributor etc.

This justification should be added as a #$ description. People must see who is this guy after reading the description and why he is here.

**Comment by yaanfpv** [comment]
Hi @limonspb . I have made the changes as requested.

**Comment by limonspb** [comment]
> Hi @limonspb . I have made the changes as requested.

Please read the message one more time :) I don't see any justification

**Comment by limonspb** [comment]
> Hi @limonspb . I have made the changes as requested.

"drone builder, researcher and tuner" that's like 98% of us, FPV hobby people :)

**Comment by yaanfpv** [comment]
Hi @limonspb . I am pretty heavily involved in the FPV community in India. I have done over 40 builds for folks and tuned over 100 quads. Folks keep asking me for tuning and rates across the FPV communities in India. Which is why I thought it will be easier if I add the rates (and soon tunes and such) to the official presets. Will help out a lot of folks.

PS: I also do shoots for big brands like Mercedes, Audi, Adidas etc (You can see glimpses of the same on my instagram YaanFPV). Putting all this in the description seemed a little self pompus, so I avoided that's all. If you still feel I should add it, I shall do the same.

**Comment by limonspb** [comment]
> Hi @limonspb . I am pretty heavily involved in the FPV community in India. I have done over 40 builds for folks and tuned over 100 quads. Folks keep asking me for tuning and rates across the FPV communities in India. Which is why I thought it will be easier if I add the rates (and soon tunes and such) to the official presets. Will help out a lot of folks.
> 
> PS: I also do shoots for big brands like Mercedes, Audi, Adidas etc (You can see glimpses of the same on my instagram YaanFPV). Putting all this in the description seemed a little self pompus, so I avoided that's all. If you still feel I should add it, I shall do the same.

Yes sir. Whatever you tell me here, plz mention some of it in the description :) at least in the end

**Pull request closed without merging**
