### PR TITLE
Added Eachine Nano V2 VTX

### PR DESCRIPTION
**Pull request by MrAlucardDante**

### CODE REVIEW

**Review by limonspb — CHANGES_REQUESTED** [review]
please mention the SmartAudio version in the description and in the keywords.
Thanks!

**Comment by MrAlucardDante** [comment]
> please mention the SmartAudio version in the description and in the keywords. Thanks!

I added the version in both.

**Review by limonspb — APPROVED** [review]

**Review by limonspb — CHANGES_REQUESTED** [review]
Please squash 3 commits in 1 commit. And its ready to go.
Please make sure you don't create a new PR for that :)

**Comment by MrAlucardDante** [comment]
Commits have been squashed

**Review by limonspb — APPROVED** [review]

**Comment by nightflasher** [comment]
hey, based on this Eachine_Nano... file, i've created an eachine_vtx only preset (integrated all the eachine possible vtx), but i can't see the preset in my repo. i've created other presets, which work fine.
somebody has some time to show me the way to success?
https://github.com/nightflasher/firmware-presets/blob/KMfpv/presets/4.3/vtx/eachine_vtx.txt

**Comment by MrAlucardDante** [comment]
> 

You might want to take a look at what I did (based on what other people did as well) and do the same :
* using groups for the power levels instead of setting bands and channels everytime, since they are the same
* create groups for EU, US and HAM, since some frequencies cannot be used in some part of the world

**Pull request merged**
