### PR TITLE
vtx table presets

### PR DESCRIPTION
**Pull request by sugaarK**
this is the VTX table collection.. ill commit brands tables as I get them to this PR

### CODE REVIEW

**Comment by ctzsnooze** [comment]
Thank you!

@mikeller do you think its OK for us to provide VTx table options via the Preset route?

**Comment by martin-korinek-1985** [comment]
Hello, I am newbie to FPV and I am currently building my 8th drone, but it is the first analog one.
I found some discrepancy about the "TBS Unify Pro32 Nano - SA 2.1" preset.
The disclaimer is stating: Note 1. Max power set to 36db...
This does not seems to be true:
https://api.betaflight.com/firmware-presets/presets/4.3/vtx/Unify_Pro32_Nano_SA2_1.txt
Have 28 instead: """vtxtable powervalues 14 20 26 28"""

Similarly:
Note 2. This table is as provided by the manufacture.
Also not true, TBS soruce:   https://www.team-blacksheep.com/vtx-table-for-betaflight.txt
//TBS Unify Pro32 Nano - SA 2.1
//max power set to 36db as it wil lforce the vtx to ouput max power
....
vtxtable powervalues 14 20 26 36
vtxtable powerlabels 25 100 400 MAX

From these information I think the 36 is the correct value, but "TBS Unify Pro32 Nano - SA 2.1" preset does not provide it.
Please correct me if I am wrong, I am aware I do not know much about analog VTXs.

**Comment by limonspb** [comment]
> Hello, I am newbie to FPV and I am currently building my 8th drone, but it is the first analog one. I found some discrepancy about the "TBS Unify Pro32 Nano - SA 2.1" preset. The disclaimer is stating: Note 1. Max power set to 36db... This does not seems to be true: https://api.betaflight.com/firmware-presets/presets/4.3/vtx/Unify_Pro32_Nano_SA2_1.txt Have 28 instead: """vtxtable powervalues 14 20 26 28"""
> 
> Similarly: Note 2. This table is as provided by the manufacture. Also not true, TBS source: https://www.team-blacksheep.com/vtx-table-for-betaflight.txt //TBS Unify Pro32 Nano - SA 2.1 //max power set to 36db as it wil lforce the vtx to ouput max power .... vtxtable powervalues 14 20 26 36 vtxtable powerlabels 25 100 400 MAX
> 
> From these information I think the 36 is the correct value, but "TBS Unify Pro32 Nano - SA 2.1" preset does not provide it. Please correct me if I am wrong, I am aware I do not know much about analog VTXs.

@sugaarK what you think?

**Comment by haslinghuis** [comment]
See: https://github.com/betaflight/firmware-presets/issues/414

**Pull request merged**
